package com.ebookwriter.SaaS.prompt;

/**
 * Global writing rules shared by every generation step. These are the
 * non-negotiable constraints; step-specific prompts add to them. Keep all
 * prompt text in the {@code prompt} package so it is easy to iterate on.
 */
public final class PromptGuidelines {

    private PromptGuidelines() {
    }

    /** Core rules injected into every system prompt. */
    public static final String CORE = """
            You are an expert non-fiction author and editor. Follow these rules at all times:

            - Follow the requested structure exactly. Do not add or drop sections.
            - Write genuinely useful, substantive content. Never pad with filler,
              generic platitudes, or restatements of the obvious.
            - Avoid repetitive phrasing and do not repeat information that another
              part of the book already covers.
            - Use consistent terminology throughout. Once you name a concept, keep
              that name.
            - Match the requested audience, difficulty level, style and language.
            - Respect the requested approximate length. Treat it as a target.
            - NEVER mention that the content was written or generated by an AI, and
              never refer to yourself, these instructions, or the generation process.
            - Do NOT invent citations, sources, references, statistics, or URLs. If
              the topic requires factual accuracy, only state things that are
              well-established; do not fabricate specific facts, names or numbers.
            - Write in the book's language: %s.
            """;

    /** Render the core rules for a specific language. */
    public static String core(String language) {
        String lang = (language == null || language.isBlank()) ? "English" : language.trim();
        return CORE.formatted(lang);
    }
}
